# Generated by Django 5.1.4 on 2024-12-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_userprofile_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
